### ISSUE TITLE
Blinding HACS

### ISSUE THREAD

**Issue by hilburn** [TilmanGriesel/graphite#30]
Hiya, just wanted to say that I love the theme generally, it's gorgeous

My one gripe is when going on the HACS page it is a blinding white that makes me jump in my seat every time it comes up

![image](https://github.com/user-attachments/assets/fe2ec5e3-84c3-416a-b2f4-e7bda7cf019f)

It'd be great if it could be modified to match the rest of the theme - or if you don't want to, if you could let me know where I should be looking for the various names to set to do it myself

**Comment by TilmanGriesel** [comment]
Hey @hilburn, thanks so much for your feedback! I'm glad you like it! The dark theme should match across all components - weird that HACS is giving you a flashbang evertyime you visit it! Mind sharing which variant of the theme variant and device / browser you're using? `Graphite`, `Graphite Light`, `Graphite Auto`. Also give cache clearing a shot if you haven't already.

This is how(tm) it should look, and how it looks for me:

![Screenshot 2024-10-30 at 17 54 13](https://github.com/user-attachments/assets/cf6be424-f0f9-45dc-b454-16bfdcadb95c)

**Comment by hilburn** [comment]
I'm using Graphite as the theme
Have cleared the cache a couple of times and reloaded firefox to no avail, have also 
It works fine on my phone though and looks like your screenshot

The only slightly weird thing I do with themes is I have an automation to set the default HA theme to Graphite on a restart
```yaml
alias: Sets default theme to Graphite
description: ""
triggers:
  - trigger: homeassistant
    event: start
conditions: []
actions:
  - action: frontend.set_theme
    metadata: {}
    data:
      mode: dark
      name: Graphite
mode: single
```
