### ISSUE TITLE
Add remove Header in Theme Patcher

### ISSUE THREAD

**Issue by Mar1usW3** [TilmanGriesel/graphite#70]
**Feature Request**  
In the past i removed the header from Homeassistant as follow in the theme
```
  card-mod-theme: "Graphite Auto"
  card-mod-root: |
    .header {
      display: none;
    }
    #view {
      padding: 0 !important;
      height: 100vh !important;
    }
```

---

### **Opportunity or Improvement**  
Would be great to have token to remove the header from the theme

**Comment by TilmanGriesel** [comment]
Hi @Mar1usW3,

Thank you for the great idea! It took some effort to integrate it into the entire theme structure and tooling, but I’m happy to share that I finally got it working on my end. Please update to the latest version and make sure to refresh your theme patcher.

```yaml
action: shell_command.patch_theme
data:
  theme: graphite-dev
  type: card-mod
  token: card-mod-root
  value: ".header{display:none;}#view{padding:0!important;height:100vh!important;}"
```

To show the header, passing any valid CSS dummy like `.header{}` should do the trick.
