### ISSUE TITLE
Theme Patcher Bug?

### ISSUE THREAD

**Issue by Mar1usW3** [TilmanGriesel/graphite#79]
**Bug Report** 

If i try to execute this with the theme patcher in Homeassistant:

```yaml
  - action: shell_command.create_token
    data:
      theme: graphite
      token: brown-color
      type: generic
      value: rgb(var(--token-rgb-red))
```
i get the following error:

`Update & Patch Graphite Theme (Advanced): Error executing script. Service not found for call_service at pos 4: Action shell_command.create_token not found`

Then i execute this, the log say it is done but nothing is done :-)

```yaml
action: shell_command.patch_theme
data:
  theme: graphite
  token: red-color
  type: generic
  value: rgb(var(--token-rgb-green))
```
if i execute:

```yaml
action: shell_command.patch_theme
data:
  theme: graphite
  token: 123-color
  type: generic
  value: rgb(var(--token-rgb-green))
this is working
```

---

### **Quick Checklist**  
- [x] I am using the latest version of Home Assistant.  
- [x] I cleared my browser cache.  
- [x] I checked the [documentation](https://www.home-assistant.io/integrations/frontend/) and existing issues.
