### ISSUE TITLE
Edit mode header background color

### ISSUE THREAD

**Issue by Misiu** [TilmanGriesel/graphite#82]
**Bug Report**  
When in edit mode the background is white:

![Image](https://github.com/user-attachments/assets/cff3c1ca-c8f2-46b1-913f-da51c6dabf1f)

---

### **Quick Checklist**  
- [x] I am using the latest version of Home Assistant.  
- [x] I cleared my browser cache.  
- [x] I checked the [documentation](https://www.home-assistant.io/integrations/frontend/) and existing issues.  

---

### **Details**  

**Home Assistant Version:**  2025.3.2

**Last Known Working Version (if any):**  
  

**Browser & OS:**  Chrome 134

**Plugins etc.:**  

---

### **The Problem**  
  
---

### **Steps to Reproduce**  

1. Go to edit mode using pencil on the top right
2. Observe the white background

---

### **Additional Information**  
In dev tools I had to add those two changes:
```CSS
.edit-mode .header {
    background-color: var(--app-header-background-color);
}
.edit-mode paper-tabs {
    background-color: var(--app-header-background-color);
}
```

With those two applied, we get:

![Image](https://github.com/user-attachments/assets/2fa44d7b-5476-4fc4-b6a5-9b4a51d12c20)

Alternative approach is to set CSS var `--app-header-edit-background-color`

EDIT:
I've edited `graphite-light.yaml` file locally, I changed
```
app-header-edit-background-color: var(--token-color-background-card)
``` 
to 
```
app-header-edit-background-color: var(--app-header-background-color)
```

and the white background is gone in edit mode
