### ISSUE TITLE
Theme Patcher script removes newline character when patching a token

### ISSUE THREAD

**Issue by rkkhanna** [TilmanGriesel/graphite#89]
**Bug Report**  
When using `shell_command.patch_theme` action to patch value of an existing token, it changes value of the token, adds `# Modified by...` comment, but removes `newline` character from end of line, thereby pulling up the next line to the end of comment and making it part of the comment.

Script action:
```
#
# Change inbuilt primary color
- action: shell_command.patch_theme
  data:
    theme: graphite
    token: token-rgb-primary
    type: rgb
    value: "{{ [  1,143,191] | join(',') }}"
```

Value of token before the change:
```
  token-rgb-primary: 224, 138, 0
  token-rgb-black: 0, 0, 0
  token-rgb-white: 240, 243, 255
```

Values after the script runs:
```
  token-rgb-primary: 1, 143, 191  # Modified by Graphite Theme Patcher v1.5.0 - 2025-04-29 17:11:12  token-rgb-black: 0, 0, 0
  token-rgb-white: 240, 243, 255
```

Note how `token-rgb-black` has been appended to the end of `# Modified by...` comment.

---

### **Quick Checklist**  
- [x] I am using the latest version of Home Assistant.  
- [x] I cleared my browser cache.  
- [x] I checked the [documentation](https://www.home-assistant.io/integrations/frontend/) and existing issues.  

---
